name: sex_91porn
description: 91Porn 视屏爬取在线播放器

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # 路由管理框架
  fluro: ^2.0.3
  #Sql数据库
  sqflite: ^2.0.0+4
  # 全局状态管理组件
  #provider: ^4.3.1
  #网络请求
  dio: ^4.0.0
  cookie_jar: 3.0.1
  dio_cookie_manager: ^2.0.0
  #权限检测器
  permission_handler: ^8.1.6
  #设备存储目录获取
  path_provider: ^2.0.3
  #持久化存储
  shared_preferences: ^2.0.8
  #Toast
  fluttertoast: ^8.0.8
  #图片放大预览
  #photo_view: ^0.10.1
  #Svg
  #flutter_svg: ^0.18.0
  #图片缓存框架
  cached_network_image: ^3.1.0
  #Html 解析器
  html: ^0.15.0
  webview_flutter_plus: ^0.2.3
  #视屏播放器
  chewie: ^1.2.2
  video_player: ^2.2.5
  #保持屏幕常亮插件
  wakelock: ^0.5.6
  #上拉加载 下拉刷新组件
  flutter_easyrefresh: ^2.2.1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/html/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
